version: 0.2

env:
    parameter-store:
        ACCESS_KEY_ID: "access_key_id"
        SECRET_ACCESS_KEY_ID: "secret_access_key"
        DB_NAME: "DB_NAME"
        DB_USER: "DB_USER"
        DB_PASSWORD: "DB_PASSWORD"
        DB_HOST: "DB_HOST"
        HOST_ADDRESS: "HOST_ADDRESS"
    variables:
        AWS_REGION: "ap-northeast-2"
        ECR_REPO_URI: "686266755470.dkr.ecr.ap-northeast-2.amazonaws.com/yesterz-service"
        
phases:
  install:
    runtime-versions:
      docker: 20

  pre_build:
    commands:
      - aws configure set aws_access_key_id $ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $SECRET_ACCESS_KEY_ID
      - aws configure set default.region $AWS_REGION
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI

  build:
    commands:
      - sed -i "s/change-db-name/$DB_NAME/g" ./Gateway_Service/Dockerfile
      - sed -i "s/change-db-user/$DB_USER/g" ./Gateway_Service/Dockerfile
      - sed -i "s/change-db-password/$DB_PASSWORD/g" ./Gateway_Service/Dockerfile
      - sed -i "s/change-db-host/$DB_HOST/g" ./Gateway_Service/Dockerfile
      - sed -i "s/change-host-address/$HOST_ADDRESS/g" ./Gateway_Service/Dockerfile
      - docker build -t yesterz-gateway ./Gateway_Service
      - docker tag yesterz-gateway $ECR_REPO_URI:gateway-1.0
      - docker push $ECR_REPO_URI:gateway-1.0
      - cat ./Gateway_Service/Dockerfile
      - sed -i "s/change-db-name/$DB_NAME/g" ./Booking_Service/Dockerfile
      - sed -i "s/change-db-user/$DB_USER/g" ./Booking_Service/Dockerfile
      - sed -i "s/change-db-password/$DB_PASSWORD/g" ./Booking_Service/Dockerfile
      - sed -i "s/change-db-host/$DB_HOST/g" ./Booking_Service/Dockerfile
      - sed -i "s/change-host-address/$HOST_ADDRESS/g" ./Booking_Service/Dockerfile
      - docker build -t yesterz-booking ./Booking_Service
      - docker tag yesterz-booking $ECR_REPO_URI:booking-1.0
      - docker push $ECR_REPO_URI:booking-1.0
      - sed -i "s/change-db-name/$DB_NAME/g" ./Hotel_Service/Dockerfile
      - sed -i "s/change-db-user/$DB_USER/g" ./Hotel_Service/Dockerfile
      - sed -i "s/change-db-password/$DB_PASSWORD/g" ./Hotel_Service/Dockerfile
      - sed -i "s/change-db-host/$DB_HOST/g" ./Hotel_Service/Dockerfile
      - sed -i "s/change-host-address/$HOST_ADDRESS/g" ./Hotel_Service/Dockerfile
      - docker build -t yesterz-hotel ./Hotel_Service
      - docker tag yesterz-hotel $ECR_REPO_URI:hotel-1.0
      - docker push $ECR_REPO_URI:hotel-1.0
      - sed -i "s/change-db-name/$DB_NAME/g" ./Loyalty_Service/Dockerfile
      - sed -i "s/change-db-user/$DB_USER/g" ./Loyalty_Service/Dockerfile
      - sed -i "s/change-db-password/$DB_PASSWORD/g" ./Loyalty_Service/Dockerfile
      - sed -i "s/change-db-host/$DB_HOST/g" ./Loyalty_Service/Dockerfile
      - sed -i "s/change-host-address/$HOST_ADDRESS/g" ./Loyalty_Service/Dockerfile
      - docker build -t yesterz-loyalty ./Loyalty_Service
      - docker tag yesterz-loyalty $ECR_REPO_URI:loyalty-1.0
      - docker push $ECR_REPO_URI:loyalty-1.0
      - sed -i "s/change-db-name/$DB_NAME/g" ./Payment_Service/Dockerfile
      - sed -i "s/change-db-user/$DB_USER/g" ./Payment_Service/Dockerfile
      - sed -i "s/change-db-password/$DB_PASSWORD/g" ./Payment_Service/Dockerfile
      - sed -i "s/change-db-host/$DB_HOST/g" ./Payment_Service/Dockerfile
      - sed -i "s/change-host-address/$HOST_ADDRESS/g" ./Payment_Service/Dockerfile
      - docker build -t yesterz-payment ./Payment_Service
      - docker tag yesterz-payment $ECR_REPO_URI:payment-1.0
      - docker push $ECR_REPO_URI:payment-1.0
      - sed -i "s/change-db-name/$DB_NAME/g" ./Report_Service/Dockerfile
      - sed -i "s/change-db-user/$DB_USER/g" ./Report_Service/Dockerfile
      - sed -i "s/change-db-password/$DB_PASSWORD/g" ./Report_Service/Dockerfile
      - sed -i "s/change-db-host/$DB_HOST/g" ./Report_Service/Dockerfile
      - sed -i "s/change-host-address/$HOST_ADDRESS/g" ./Report_Service/Dockerfile
      - docker build -t yesterz-report ./Report_Service
      - docker tag yesterz-report $ECR_REPO_URI:report-1.0
      - docker push $ECR_REPO_URI:report-1.0
      - sed -i "s/change-db-name/$DB_NAME/g" ./Session_Service/Dockerfile
      - sed -i "s/change-db-user/$DB_USER/g" ./Session_Service/Dockerfile
      - sed -i "s/change-db-password/$DB_PASSWORD/g" ./Session_Service/Dockerfile
      - sed -i "s/change-db-host/$DB_HOST/g" ./Session_Service/Dockerfile
      - sed -i "s/change-host-address/$HOST_ADDRESS/g" ./Session_Service/Dockerfile
      - docker build -t yesterz-session ./Session_Service
      - docker tag yesterz-session $ECR_REPO_URI:session-1.0
      - docker push $ECR_REPO_URI:session-1.0
      - sed -i "s/change-db-name/$DB_NAME/g" ./Rating_Service/Dockerfile
      - sed -i "s/change-db-user/$DB_USER/g" ./Rating_Service/Dockerfile
      - sed -i "s/change-db-password/$DB_PASSWORD/g" ./Rating_Service/Dockerfile
      - sed -i "s/change-db-host/$DB_HOST/g" ./Rating_Service/Dockerfile
      - sed -i "s/change-host-address/$HOST_ADDRESS/g" ./Rating_Service/Dockerfile
      - docker build -t yesterz-rating ./Rating_Service
      - docker tag yesterz-rating $ECR_REPO_URI:rating-1.0
      - docker push $ECR_REPO_URI:rating-1.0

