apiVersion: apps/v1 
kind: Deployment 
metadata:
 name: rating-api
 namespace: yesterz-service
spec: 
 replicas: 2 
 selector:
  matchLabels:
   app: rating-api
 template:
  metadata: 
   labels:
    app: rating-api
  spec:
   containers:
    - name: rating-api
      image: 686266755470.dkr.ecr.ap-northeast-2.amazonaws.com/yesterz-service:rating-1.08
      imagePullPolicy: Always
      ports:
        - containerPort: 8007