apiVersion: apps/v1 
kind: Deployment 
metadata:
 name: hotel-api
 namespace: yesterz-service
spec: 
 replicas: 2 
 selector:
  matchLabels:
   app: hotel-api
 template:
  metadata: 
   labels:
    app: hotel-api
  spec:
   containers:
    - name: hotel-api
      image: 686266755470.dkr.ecr.ap-northeast-2.amazonaws.com/yesterz-service:hotel-1.08
      imagePullPolicy: Always
      ports:
        - containerPort: 8004