apiVersion: apps/v1 
kind: Deployment 
metadata:
 name: loyalty-api
 namespace: yesterz-service
spec: 
 replicas: 2 
 selector:
  matchLabels:
   app: loyalty-api
 template:
  metadata: 
   labels:
    app: loyalty-api
  spec:
   containers:
    - name: loyalty-api
      image: 686266755470.dkr.ecr.ap-northeast-2.amazonaws.com/yesterz-service:loyalty-1.08
      imagePullPolicy: Always
      ports:
        - containerPort: 8000