apiVersion: v1
kind: Service 
metadata:
 name: payment-api
 namespace: yesterz-service
spec:
 selector:
  app: payment-api
 type: NodePort 
 ports:
  - name: payment-port
    protocol: TCP 
    port: 8002
    targetPort: 8002