apiVersion: v1
kind: Service 
metadata:
 name: gateway-api
 namespace: yesterz-service
spec:
 selector:
  app: gateway-api
 type: NodePort 
 ports:
  - name: gateway-port
    protocol: TCP 
    port: 8005
    targetPort: 8005