apiVersion: v1
kind: Service 
metadata:
 name: session-api
 namespace: yesterz-service
spec:
 selector:
  app: session-api
 type: NodePort
 ports:
  - name: session-port
    protocol: TCP 
    port: 8001
    targetPort: 8001